from __future__ import annotations

from enum import Enum


class PovMode(str, Enum):
    FIRST = "First"
    THIRD_LIMITED = "Third_Limited"
    THIRD_OMNI = "Third_Omni"


class StoryStructure(str, Enum):
    SAVE_THE_CAT = "SAVE_THE_CAT"
    THREE_ACT = "THREE_ACT"
    HERO_JOURNEY = "HERO_JOURNEY"
    FREYTAGS_PYRAMID = "FREYTAGS_PYRAMID"
    KISHOTENKETSU = "KISHOTENKETSU"
    FICHTEAN_CURVE = "FICHTEAN_CURVE"
    SEVEN_POINT_STRUCTURE = "SEVEN_POINT_STRUCTURE"
    SEVEN_KEY_STEPS = "SEVEN_KEY_STEPS"
    SNOWFLAKE_METHOD = "SNOWFLAKE_METHOD"
    BRAINDUMP = "BRAINDUMP"
    OTHER = "OTHER"


class JobPhase(str, Enum):
    P_100 = "P-100"
    P_200 = "P-200"
    P_300 = "P-300"
    P_400 = "P-400"


class JobStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class StoryFlowStageConfigurationState(str, Enum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    OPTIONAL = "OPTIONAL"
    ARCHIVED = "ARCHIVED"


class StoryFlowStageProgressState(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    COMPLETE = "COMPLETE"
    SUPERSEDED = "SUPERSEDED"


class StoryArtifactLifecycleState(str, Enum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    CANONICAL = "CANONICAL"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class StorySuggestionLifecycleState(str, Enum):
    REQUESTED = "REQUESTED"
    READY = "READY"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    REFINE_REQUESTED = "REFINE_REQUESTED"
    EXPIRED = "EXPIRED"


class StoryBranchState(str, Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class StoryDecisionNodeType(str, Enum):
    DECISION = "DECISION"
    BRANCH_POINT = "BRANCH_POINT"
    MERGE = "MERGE"


class StoryDecisionChangeType(str, Enum):
    ARC_SELECTION = "ARC_SELECTION"
    ARC_PIVOT = "ARC_PIVOT"
    STORY_DEVIATION = "STORY_DEVIATION"
    STAGE_RENAME = "STAGE_RENAME"
    STAGE_REDEFINE = "STAGE_REDEFINE"
    STAGE_REORDER = "STAGE_REORDER"
    STAGE_CONFIGURATION = "STAGE_CONFIGURATION"
    FOUNDATION_REVISION = "FOUNDATION_REVISION"
    CHARACTER_REVISION = "CHARACTER_REVISION"
    WORLD_BIBLE_REVISION = "WORLD_BIBLE_REVISION"
    PLANNING_PIVOT = "PLANNING_PIVOT"
    BRANCH_CREATED = "BRANCH_CREATED"
    BRANCH_ACTIVATED = "BRANCH_ACTIVATED"
    BRANCH_MERGED = "BRANCH_MERGED"


class StoryObjectType(str, Enum):
    STORY_FLOW_DEFINITION = "STORY_FLOW_DEFINITION"
    STORY_FLOW_STAGE = "STORY_FLOW_STAGE"
    FOUNDATION_PROFILE = "FOUNDATION_PROFILE"
    FOUNDATION_REVISION = "FOUNDATION_REVISION"
    CHARACTER_PROFILE = "CHARACTER_PROFILE"
    RELATIONSHIP_EDGE = "RELATIONSHIP_EDGE"
    WORLD_BIBLE_ENTRY = "WORLD_BIBLE_ENTRY"
    ARC_CANDIDATE = "ARC_CANDIDATE"
    ARC_COMPARISON_RECORD = "ARC_COMPARISON_RECORD"
    ARC_SELECTION = "ARC_SELECTION"
    ARC_STAGE_MAP = "ARC_STAGE_MAP"
    BEAT_PLAN = "BEAT_PLAN"
    SEQUENCE_PLAN = "SEQUENCE_PLAN"
    CHAPTER_PLAN = "CHAPTER_PLAN"
    SCENE_PLAN = "SCENE_PLAN"
    CHAPTER_PACKET = "CHAPTER_PACKET"
    STORY_BRANCH = "STORY_BRANCH"
    BRANCH_POINT = "BRANCH_POINT"
    DRAFT_ARTIFACT = "DRAFT_ARTIFACT"
    MANUSCRIPT_DOCUMENT = "MANUSCRIPT_DOCUMENT"
    REVISION_SUGGESTION = "REVISION_SUGGESTION"
    REVIEW_DECISION = "REVIEW_DECISION"
    CHECKER_FINDING = "CHECKER_FINDING"


class BrainstormItemTypes(str, Enum):
    CHARACTER = "CHARACTER"
    LOCATION = "LOCATION"
    PLOT_POINT = "PLOT_POINT"
    THEME = "THEME"
    CONFLICT = "CONFLICT"
    WORLD_BUILDING = "WORLD_BUILDING"
    DIALOGUE = "DIALOGUE"
    RELATIONSHIP = "RELATIONSHIP"
    OBJECT = "OBJECT"
    RULE = "RULE"
