from __future__ import annotations

from typing import Protocol


class PlanningRepository(Protocol):
    def upsert_sequence_plan(self, *args, **kwargs): ...
    def get_sequence_plan(self, *args, **kwargs): ...
    def list_sequence_plans(self, *args, **kwargs): ...
    def upsert_chapter_plan(self, *args, **kwargs): ...
    def get_chapter_plan(self, *args, **kwargs): ...
    def list_chapter_plans(self, *args, **kwargs): ...
    def upsert_scene_plan(self, *args, **kwargs): ...
    def get_scene_plan(self, *args, **kwargs): ...
    def list_scene_plans(self, *args, **kwargs): ...
    def upsert_beat_plan(self, *args, **kwargs): ...
    def get_beat_plan(self, *args, **kwargs): ...
    def list_beat_plans(self, *args, **kwargs): ...
    def upsert_planning_dependency(self, *args, **kwargs): ...
    def get_planning_dependency(self, *args, **kwargs): ...
    def list_planning_dependencies(self, *args, **kwargs): ...
    def upsert_chapter_packet(self, *args, **kwargs): ...
    def get_chapter_packet(self, *args, **kwargs): ...
    def list_chapter_packets(self, *args, **kwargs): ...


class BranchingRepository(Protocol):
    def record_story_decision_node(self, *args, **kwargs): ...
    def get_story_decision_node(self, *args, **kwargs): ...
    def list_story_decision_nodes(self, *args, **kwargs): ...
    def upsert_branch_point(self, *args, **kwargs): ...
    def get_branch_point(self, *args, **kwargs): ...
    def get_branch_point_for_source_node(self, *args, **kwargs): ...
    def list_branch_points(self, *args, **kwargs): ...
    def upsert_story_branch(self, *args, **kwargs): ...
    def get_story_branch(self, *args, **kwargs): ...
    def list_story_branches(self, *args, **kwargs): ...
    def get_active_story_branch(self, *args, **kwargs): ...
    def set_active_story_branch(self, *args, **kwargs): ...
    def upsert_branch_state_ref(self, *args, **kwargs): ...
    def get_branch_state_ref(self, *args, **kwargs): ...
    def list_branch_state_refs(self, *args, **kwargs): ...
    def upsert_branch_comparison(self, *args, **kwargs): ...
    def get_branch_comparison(self, *args, **kwargs): ...
    def list_branch_comparisons(self, *args, **kwargs): ...
    def upsert_branch_merge_decision(self, *args, **kwargs): ...
    def get_branch_merge_decision(self, *args, **kwargs): ...
    def list_branch_merge_decisions(self, *args, **kwargs): ...


class ReviewRepository(Protocol):
    def upsert_checker_finding(self, *args, **kwargs): ...
    def get_checker_finding(self, *args, **kwargs): ...
    def list_checker_findings(self, *args, **kwargs): ...
    def list_checker_findings_for_source(self, *args, **kwargs): ...
    def upsert_review_decision(self, *args, **kwargs): ...
    def get_review_decision(self, *args, **kwargs): ...
    def list_review_decisions(self, *args, **kwargs): ...
    def list_review_decisions_for_target(self, *args, **kwargs): ...
    def upsert_inspect_run_link(self, *args, **kwargs): ...
    def get_inspect_run_link(self, *args, **kwargs): ...
    def list_inspect_run_links(self, *args, **kwargs): ...
    def list_inspect_run_links_for_object(self, *args, **kwargs): ...
    def list_inspect_run_links_for_run(self, *args, **kwargs): ...
    def list_inspect_run_links_for_logical_run(self, *args, **kwargs): ...


class ContinuityRepository(Protocol):
    def upsert_continuity_thread(self, *args, **kwargs): ...
    def get_continuity_thread(self, *args, **kwargs): ...
    def list_continuity_threads(self, *args, **kwargs): ...
    def upsert_continuity_state(self, *args, **kwargs): ...
    def get_continuity_state(self, *args, **kwargs): ...
    def list_continuity_states(self, *args, **kwargs): ...
    def upsert_continuity_finding(self, *args, **kwargs): ...
    def get_continuity_finding(self, *args, **kwargs): ...
    def list_continuity_findings(self, *args, **kwargs): ...
    def upsert_draft_brief(self, *args, **kwargs): ...
    def get_draft_brief(self, *args, **kwargs): ...
    def list_draft_briefs(self, *args, **kwargs): ...
    def upsert_drafting_context_packet(self, *args, **kwargs): ...
    def get_drafting_context_packet(self, *args, **kwargs): ...
    def list_drafting_context_packets(self, *args, **kwargs): ...


class DraftingRepository(Protocol):
    def upsert_draft_artifact(self, *args, **kwargs): ...
    def get_draft_artifact(self, *args, **kwargs): ...
    def list_draft_artifacts(self, *args, **kwargs): ...
    def upsert_manuscript_document(self, *args, **kwargs): ...
    def get_manuscript_document(self, *args, **kwargs): ...
    def list_manuscript_documents(self, *args, **kwargs): ...
    def upsert_revision_suggestion(self, *args, **kwargs): ...
    def get_revision_suggestion(self, *args, **kwargs): ...
    def list_revision_suggestions(self, *args, **kwargs): ...
    def list_revision_suggestions_for_document(self, *args, **kwargs): ...


class GenerationRepository(Protocol):
    def upsert_canon_generation_run(self, *args, **kwargs): ...
    def get_canon_generation_run(self, *args, **kwargs): ...
    def list_canon_generation_runs(self, *args, **kwargs): ...
    def upsert_canon_generation_packet(self, *args, **kwargs): ...
    def get_canon_generation_packet(self, *args, **kwargs): ...
    def list_canon_generation_packets_for_generation(self, *args, **kwargs): ...
    def upsert_generation_gate_result(self, *args, **kwargs): ...
    def get_generation_gate_result(self, *args, **kwargs): ...
    def list_generation_gate_results(self, *args, **kwargs): ...


class ManuscriptAssistRepository(Protocol):
    def upsert_manuscript_assist_run(self, *args, **kwargs): ...
    def get_manuscript_assist_run(self, *args, **kwargs): ...
    def list_manuscript_assist_runs(self, *args, **kwargs): ...
    def upsert_manuscript_assist_suggestion(self, *args, **kwargs): ...
    def get_manuscript_assist_suggestion(self, *args, **kwargs): ...
    def list_manuscript_assist_suggestions(self, *args, **kwargs): ...
    def update_manuscript_assist_suggestion_status(self, *args, **kwargs): ...
    def upsert_manuscript_assist_gate_result(self, *args, **kwargs): ...
    def get_manuscript_assist_gate_result(self, *args, **kwargs): ...
    def list_manuscript_assist_gate_results(self, *args, **kwargs): ...


class CanonRepository(Protocol):
    def upsert_canon_annotation(self, *args, **kwargs): ...
    def get_canon_annotation(self, *args, **kwargs): ...
    def list_canon_annotations(self, *args, **kwargs): ...
    def delete_canon_annotation(self, *args, **kwargs): ...
    def upsert_canon_customization_profile(self, *args, **kwargs): ...
    def get_canon_customization_profile(self, *args, **kwargs): ...
    def list_canon_customization_profiles(self, *args, **kwargs): ...
    def delete_canon_customization_profile(self, *args, **kwargs): ...


class LibraryRepository(Protocol):
    def upsert_mythos_entry(self, *args, **kwargs): ...
    def get_mythos_entry(self, *args, **kwargs): ...
    def list_mythos_entries(self, *args, **kwargs): ...
    def delete_mythos_entry(self, *args, **kwargs): ...
    def upsert_pattern_entry(self, *args, **kwargs): ...
    def get_pattern_entry(self, *args, **kwargs): ...
    def list_pattern_entries(self, *args, **kwargs): ...
    def delete_pattern_entry(self, *args, **kwargs): ...
